spring:
  mail:
    host: smtp.gmail.com
    port: 700
    username: bank.project.random@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
